apiVersion: v1
kind: Service
metadata:
  name: vehicle-sales-service
spec:
  selector:
    app: vehicle-sales-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP
